name: Auto-Sync fork with upstream

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v4
      with:
        ref: master
        token: ${{ secrets.PAT }}
        
    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: master
        # REQUIRED 'target_repo_token' exactly like this!
        target_repo_token: ${{ secrets.PAT }}
        upstream_sync_branch: master
        upstream_sync_repo: DIYgod/RSSHub

        # Set test_mode true to run tests instead of the true action!!
        test_mode: false

    - name: Timestamp
      run: date
